#!/bin/sh
set -eu

repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
preferences_dir="$repo_root/docs/conductor-preferences"
repo_name="${CONDUCTOR_REPO_NAME:-$(basename "$repo_root")}"

mkdir -p "$preferences_dir"

cat > "$preferences_dir/README.md" <<'EOF'
# Conductor preferences (generated)

This directory is regenerated by `conductor.json`'s setup script on every
workspace creation. Paste each file's content into Settings (⌘,) →
EOF
printf '%s\n' "$repo_name → Preferences, once per machine." >> "$preferences_dir/README.md"
cat >> "$preferences_dir/README.md" <<'EOF'

| File | Field |
|---|---|
| `code-review.md` | Code Review |
| `create-pr.md` | Create PR |
| `branch-rename.md` | Branch rename |

Skill paths are provisioned automatically into `~/.claude/skills/` by hyprlayer.
EOF

cat > "$preferences_dir/code-review.md" <<'EOF'
Use ~/.claude/skills/code_review/SKILL.md as the review procedure — read it first, then follow its tier dispatch (Codex CLI if present, else the adversarial-reviewer subagent).

Acquire the diff via `mcp__conductor__GetWorkspaceDiff` (start with `stat: true`, then request files) — do not shell out to `git diff` unless the MCP tool is unavailable.

Post each finding as a single `mcp__conductor__DiffComment` call so it surfaces inline in the Conductor review panel. Then print the same numbered list to the chat so I can scan it without expanding every comment.
EOF

cat > "$preferences_dir/create-pr.md" <<'EOF'
Before composing the PR title and body, read and follow ~/.claude/skills/describe_pr/SKILL.md. It uses this repo's pr_description.md template and applies the project's commit/PR conventions (no Co-Authored-By trailer, lowercase subject prefixes, automated-verification block populated from real command output).

Keep Conductor's default mechanics for everything else: commit any pending changes, push to the upstream branch, then `gh pr create --base <target>`. Use `mcp__conductor__GetWorkspaceDiff` for the diff that informs the body — do not re-derive the diff from `git diff` unless the MCP tool is unavailable.

If the user has already approved a PR title/body in a prior turn, do not re-author — pass that text straight to `gh pr create`.
EOF

cat > "$preferences_dir/branch-rename.md" <<'EOF'
Rename the branch to a short kebab-case slug. If the work is tied to a JIRA ticket (ENG-XXXX style), prefix the slug with the ticket key (e.g. ENG-1478-parent-child-tracking). Otherwise, just feature/<slug> matching the work's intent. No timestamps, no author initials.
EOF
